### ISSUE TITLE
Remove dependency on Composer

### ISSUE THREAD

**Issue by still-dreaming-1** [phpvim/phpcd.vim#40]
As far as I understand it, there is no reason for this project to depend on Composer. It seems that all Composer does is place the code from external dependencies and extra autoloads for them inside a vendor/ directory. But some projects don't have any external dependencies, so I don't understand why this depends on Composer. Even if a project did have external dependencies, it is very likely that most of the code is internal to that project. My point is that phpcd.vim will have to work correctly with this internal code anyway, even the parts of it that don't have external dependencies, so it does not seem that Composer is core to how phpcd.vim works. Even if a project did have external dependencies it could get them to work by placing the code inside the project and getting it to work with their internal code the same way they get their internal code to work with the internal code, which phpcd.vim has to know how to work correctly with anyway.

**Comment by przepompownia** [comment]
I agree with you but it need some refactoring. 

Please look at the branch 
https://github.com/phpvim/phpcd.vim/tree/complete_class_names+standalone-rpc
especially at `complete_class_names`. 

This branch has not only functionality compliant with its name, but it also makes steps to extract an interface of any repository made to find classes that matches given pattern. It is named `ClassInfoRepository` and at this moment it has only significant method `find()`. This abstract method has still not specified interface of each "class info entity" from returned array. 

Now we have only one working implementation (`ComposerClassmapFileRepository`) in this branch but just now we can create another its implementation that may be independent of Composer and use it without changing `ComposerClassmapFileRepository`. 

Interface `ClassInfoRepository` still has no method related to storing. Maybe, for performance reasons, we should have two repository interfaces: the first for queries only (like the existing interface, excluding `reload`), the second for "commands" (something like create, update, delete). 

As you can see, the new proposition is not complete, it has still unstable interface but it is more open to create alternative implementations of repositories (i.e. how to retrieve information from a storage, how to retrieve information from the project and update the storage). 

We probably need to have separate repositories to find functions and constants defined beyond classes because of examples as below:
```
    const A = 3;
    function A(){ }
    class A {}
```

**Comment by still-dreaming-1** [comment]
@przepompownia Good to know you are thinking along the same lines. Maybe I will try to become a contributor one of these days.

**Comment by lvht** [comment]
Fixed by 47194e714e3e2b21ee0a84fd772e130479327aa3
